[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"

# Use latest Gatsby plugin version compatible with Gatsby 5
[[plugins]]
  package = "@netlify/plugin-gatsby"

[build.environment]
  NODE_VERSION = "22"
  # Configure secrets scanning to ignore generated files
  SECRETS_SCAN_OMIT_PATHS = "public/**,static/admin/config.yml"
  
[build.cache]
  paths = [
    "node_modules"
  ]